int NUM_DATA = 15;
Example[NUM_DATA] examples = {
new Example(x = 0, y = 0, v = 0)
, new Example(x = 1, y = 0, v = 0)
, new Example(x = 2, y = 0, v = 0)
, new Example(x = 3, y = 0, v = 0)
, new Example(x = 4, y = 0, v = 0)
, new Example(x = 0, y = 1, v = 1)
, new Example(x = 1, y = 1, v = 1)
, new Example(x = 2, y = 1, v = 1)
, new Example(x = 3, y = 1, v = 1)
, new Example(x = 4, y = 1, v = 1)
, new Example(x = 0, y = 2, v = 0)
, new Example(x = 1, y = 2, v = 0)
, new Example(x = 2, y = 2, v = 0)
, new Example(x = 3, y = 2, v = 0)
, new Example(x = 4, y = 2, v = 0)
};

#include "cad.sk"

harness void main(int i) {
  assume (0 <= i && i < NUM_DATA);
  Program solution = gen(DEPTH);
  Vector v = new Vector(x = examples[i].x, y = examples[i].y);
  assert (eval(solution, v) == examples[i].v);
}                    
                    
